Update SDK with the new config update
CESARBR/knot-cloud-sdk-js-amqp pull request #25
Opened 2020-09-10 20:03 UTC by Igoraamc

**Describe what this PR introduces:** (if necessary, link currently open issues with [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords))

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:
         Update config event.

**Does this PR introduce any breaking changes?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [x] New/updated tests are included

**Testing environment:**

- Operating System/Platform: macOS Catalina
- Node version: v12.16.0
- Yarn version: 1.22.0

If you have relevant logs, error output and etc, please attach them.

**Other information:**

2020-09-10 22:31 UTC, asf89 approved these changes
LGTM!

2020-09-12 23:20 UTC, esdrasjnr approved these changes
Looks great! 👍🏻 💯 Just left one little request, let me know if you agree 😉

2020-09-12 23:20 UTC, esdrasjnr commented on README.md
> +  * `schema` **JSON Object** Schema item, each one formed by:
I think that `Schema item, formed by` is enough. I think that with "each one" seems there is more than one schema object

2020-09-12 23:20 UTC, esdrasjnr commented on README.md
> +  * `event` **JSON Object** Event item, each one formed by:
Same here

2020-09-14 15:32 UTC, Igoraamc commented on README.md
> +  * `event` **JSON Object** Event item, each one formed by:
Done!

2020-09-14 15:32 UTC, Igoraamc commented on README.md
> +  * `schema` **JSON Object** Schema item, each one formed by:
Done!

2020-09-15 22:03 UTC, netoax requested changes
Add a commit bumping this package version to `3.0.0` and update the CHANGELOG with the changes description.

2020-09-17 01:25 UTC, netoax approved these changes
LGTM!

2020-09-17 01:26 UTC, merged